# This is a basic workflow to help you get started with Actions

name: Minecraft-Packr

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "check-bats-version"
  check-bats-version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Build & Upload Packs
        uses: Sindercube/Packr@v2
        with:

          github-repo: ${{ github.event.repository.full_name }}
          release-version: ${{ github.event.release.tag_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
