name: build-Minecraft-resources-pack-And-release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # push:
  #   tags:
  #   - '*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job calle
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: build resources pack
        run: |
          zip -r Translation-zh_tw-of-masa-series-mods.zip assets/ pack.mcmeta pack.png mod-list.md

      - name: upload
        uses: ncipollo/release-action@v1.14.0
        with:
          # allowUpdates: true
          # removeArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "Translation-zh_tw-of-masa-series-mods.zip"
